export default interface InputComponentProps {
  name: string;
  label?: string;
  placeholder?: string;
  fontFamily?: string;
  color?: string;
  labelColor?: string;
  paddingLeft?: number;
  textColor?: string;
  width?: number;
  secureTextEntry?: boolean;
  mode?: string;
  value: string;
  textAlign?: string;
  fontSize?: number;
  keyboardTypeNumeric?: boolean;
  setValue(text: string): void;
  onBlur?: () => void;
  onFocus?: () => void;
  onPressIcon?: () => void;
  selectionColor?: string;
  underlineColor?: string;
  background?: string;
  inputMaskMoney?: boolean;
  error?: boolean;
  fontStyle?: string;
  marginBottom?: number;
  errorMessage?: string | null;
  icon?: boolean;
  iconColor?: string;
  mask?: string;
  marginLeft?: number;
  alignText?: string;
  placeholderTextColor?: string;
  fontWeight?: string;
  password?: boolean;
  isValid?: boolean;
  borderColor?: string;
  borderRadius?: number;
  testID?: string;
  sizeIcon?: number;
  multiline?: boolean;
  numberOfLines?: number;
  Callback?: () => void;
  iconName?: string | null;
  borderWidth?: number;
  marginHorizontal?: number;
  maxLength?: number;
  height?: number;
  iconMaterial?: boolean;
  iconMaterialCommunityIcons?: boolean;
  iconAntDesign?: boolean;
  iconEntypo?: boolean;
  iconEvilIcons?: boolean;
  iconFeather?: boolean;
  iconFontAwesome?: boolean;
  iconFontAwesome5?: boolean;
  iconFontisto?: boolean;
  iconFoundation?: boolean;
  iconIonicons?: boolean;
}
